# Generated by Django 5.2.10 on 2026-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.CharField(max_length=500)),
                ('Conditions', models.CharField(max_length=20)),
                ('Confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('RecommendedDrug', models.CharField(max_length=50)),
                ('Pre_Date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Predictionss',
            },
        ),
    ]
